; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
; lib_extra_dirs = C:\Users\atoru\OneDrive\workplace\Arduino
monitor_speed = 115200
upload_port = com6
monitor_port = com6
lib_deps = knolleary/PubSubClient@^2.8
debug_tool = esp-bridge
debug_speed = 5000
debug_init_break = tbreak setup
build_type = debug

[env:esp32dev-ota]
extends = env:esp32dev
upload_protocol = espota
; ESP32のIPアドレスまたはmDNSホスト名(esp32-vst.local)を指定
; upload_port = 192.168.0.168
upload_port = esp32-vst.local   ; ← IPアドレスではなくホスト名を指定
; 必要に応じてポートや認証パスワードを設定可能
; upload_flags =
;   --port=3232
;   --auth=password

