; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs = C:\Users\qubil\OneDrive\workplace\Arduino
lib_deps = knolleary/PubSubClient@^2.8
monitor_speed = 115200
; debug_tool = minimodule
; upload_protocol = minimodule
; debug_init_break = tbreak setup
upload_port = com39
monitor_port = com39
; upload_port = COM31
; monitor_port = COM31
; upload_port = COM32
; monitor_port = COM32
; upload_port = COM4
; monitor_port = COM4
; upload_port = COM8
; monitor_port = COM8

; upload_port = /dev/cu.usbserial-00000000
; monitor_port = /dev/cu.usbserial-00000000
; upload_port = /dev/cu.usbserial-A50285BI
; monitor_port = /dev/cu.usbserial-A50285BI
; upload_port = /dev/cu.usbserial-2
; monitor_port = /dev/cu.usbserial-2
; upload_port = minimodule
; monitor_port = minimodule
; debug_tool = minimodule